---
platforms:
  go_vet:
    name: ":go: vet"
    platform: ubuntu1804
    shell_commands:
      - go vet github.com/bazelbuild/bazelisk/...
      - go get -u golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
      - go vet -vettool=$(which shadow) github.com/bazelbuild/bazelisk/...
  ubuntu1604:
    build_targets:
      - //...
    test_targets:
      - //...
    test_flags:
      - --flaky_test_attempts=1
      - --test_output=streamed
  ubuntu1804:
    build_targets:
      - //...
    test_targets:
      - //...
    test_flags:
      - --flaky_test_attempts=1
      - --test_output=streamed
  macos:
    build_targets:
      - //...
    test_targets:
      - //...
    test_flags:
      - --flaky_test_attempts=1
      - --test_output=streamed
  windows:
    build_targets:
      - //...
    test_targets:
      - //...
      # Windows doesn't have a `python3` executable on PATH.
      - -//:py3_bazelisk_test
    test_flags:
      - --flaky_test_attempts=1
      - --test_env=PATH
      - --test_env=PROCESSOR_ARCHITECTURE
      - --test_output=streamed
